language: ruby
rvm:
- jruby-1.7.20
before_install:
- gem install bundler -v 1.10.1
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: J3/E3dTIv1ZkCLLbDj0EJVh5toxHOACsqjTuoUjwnV0dc6GQsqhlgxxOebtOU+LMyO7WaXncPH9Yy3zYpI2G7hulOczGiF+9JG1SqysMg0RS5LX0lyZlE8UPb/C3ILKPAbMfyrp/dMhS+9M36p6ZOjtS2PMXVgAi/tUUvFEgXLmoi1yzfbG1Dy0JLOURPgLdKgXdV54VxxPb/V3YZXq2S0XVu5MTDQOJoblYJ6RyBfkFVcDoSFI3qBUD6m2xmw1qpv0rfiKEZmiImpTi1/jOIxBEIIARBi0X1RWM1p/mOcXxiWMpJ925crYftibd39acuAO2bIMiYyeevB76QhM4va+OlQ1/yHe85EibixH+kRL7Xd99j+Ouwdpa6m14M8NWFo2Lx3Rr99MjAYeDNMV++OBS3KBMmyAZIqA/sosAjnzMeZHFKRxRMdkZW1/AFHkXVcOFYIIGn83l0ciLBFpjRnDimBN2KVA6Alslu7+qPGEuQKTSEpVZF1uNui+tF1z/MgnllX1IMnNN4RODNbYKAUc+drL2nRit1QCnUAR7BYZ7Q4LcmcSmnGX2dPD1ovUSbiCNDbWCDecZAd2TFqbMn9Bgx9jHyNgfo4yEednDgrYmk1OGNExIunWJckirYBhYGDQN4Lv39Kb4Xyqe4jV35HvYVZIKBwnSyHIfwJykFeA=
after_success:
- coveralls
addons:
  code_climate:
    repo_token:
      secure: vzwI+AOiJguz+WBpkjrKZg3WRhVoOefFN2QHb1OqREiD9lewxGAD13d2xAphUU8V+rimUBzaSTwj3pdJ3/Ap11Y05IqRcaLE9E+fvWj4sRRHWR5l8A4KLlQKE11erHfBa2EC8jrh00MrtBsNU37e10YvXQhN2XsPQI+1QG8RGUDjZ0yFXVPoDbnzLw7q333nzbz5zpzcBCgfTxljaO6oNG1MzRgs0l/To/oJV9pyHtYkHALIUjlt9racBDG+i+EehrzqmBKHWDKYpOW6Yzy158Fz8w8BVw7dabDXyfxSp9r0YFK0Ca8V1GCvMD3YNh8zG1EgH9cRWgaI1dscof1MAT4YpAy978D0/c0ssKHF3ElAT+3InlirtZr9kMN4lTLwAgGlTsERW6qKc/mroh6axCftY2NFJeWe9rnt+z9GHfUO6tZZ5Y5VY/zngBJkZDyL0sDxCg3IkD7EeCRqbP/IMUkateMn9Ju7zNT0l4Pva6a+vEWOv20+U7EYJ0sBAEsXejo+fy0+lN9tzxF/H2es2HCmwBabcV1qHUHsrSS17+S37djxeW8/MKdepk2jFA6AULVkuITUezWxAxUPNeqED/nSO90iN488CLv6pf7uiAwbv0kooKqsN0HPjI/bqw1R5h2kwBcRrNoHQ63Ndf+UWznVSanF1sYct0GcV/CPmOo=
cache: bundler